export interface Currency {
  code: string;
  symbol: string;
  name: string;
  numericCode: string;
}

// Top 100 most commonly used fiat currencies
export const CURRENCIES: Currency[] = [
  { code: 'USD', symbol: '$', name: 'United States Dollar', numericCode: '840' },
  { code: 'EUR', symbol: '€', name: 'Euro', numericCode: '978' },
  { code: 'JPY', symbol: '¥', name: 'Japanese Yen', numericCode: '392' },
  { code: 'GBP', symbol: '£', name: 'British Pound Sterling', numericCode: '826' },
  { code: 'CNY', symbol: '¥', name: 'Chinese Yuan', numericCode: '156' },
  { code: 'CAD', symbol: 'C$', name: 'Canadian Dollar', numericCode: '124' },
  { code: 'AUD', symbol: 'A$', name: 'Australian Dollar', numericCode: '036' },
  { code: 'CHF', symbol: 'CHF', name: 'Swiss Franc', numericCode: '756' },
  { code: 'INR', symbol: '₹', name: 'Indian Rupee', numericCode: '356' },
  { code: 'BRL', symbol: 'R$', name: 'Brazilian Real', numericCode: '986' },
  { code: 'MXN', symbol: '$', name: 'Mexican Peso', numericCode: '484' },
  { code: 'KRW', symbol: '₩', name: 'South Korean Won', numericCode: '410' },
  { code: 'SGD', symbol: 'S$', name: 'Singapore Dollar', numericCode: '702' },
  { code: 'HKD', symbol: 'HK$', name: 'Hong Kong Dollar', numericCode: '344' },
  { code: 'SEK', symbol: 'kr', name: 'Swedish Krona', numericCode: '752' },
  { code: 'NOK', symbol: 'kr', name: 'Norwegian Krone', numericCode: '578' },
  { code: 'DKK', symbol: 'kr', name: 'Danish Krone', numericCode: '208' },
  { code: 'PLN', symbol: 'zł', name: 'Polish Złoty', numericCode: '985' },
  { code: 'TRY', symbol: '₺', name: 'Turkish Lira', numericCode: '949' },
  { code: 'RUB', symbol: '₽', name: 'Russian Ruble', numericCode: '643' },
  { code: 'ZAR', symbol: 'R', name: 'South African Rand', numericCode: '710' },
  { code: 'THB', symbol: '฿', name: 'Thai Baht', numericCode: '764' },
  { code: 'MYR', symbol: 'RM', name: 'Malaysian Ringgit', numericCode: '458' },
  { code: 'IDR', symbol: 'Rp', name: 'Indonesian Rupiah', numericCode: '360' },
  { code: 'PHP', symbol: '₱', name: 'Philippine Peso', numericCode: '608' },
  { code: 'ILS', symbol: '₪', name: 'Israeli Shekel', numericCode: '376' },
  { code: 'AED', symbol: 'د.إ', name: 'United Arab Emirates Dirham', numericCode: '784' },
  { code: 'SAR', symbol: 'ر.س', name: 'Saudi Riyal', numericCode: '682' },
  { code: 'QAR', symbol: 'ر.ق', name: 'Qatari Riyal', numericCode: '634' },
  { code: 'KWD', symbol: 'د.ك', name: 'Kuwaiti Dinar', numericCode: '414' },
  { code: 'BHD', symbol: '.د.ب', name: 'Bahraini Dinar', numericCode: '048' },
  { code: 'OMR', symbol: 'ر.ع.', name: 'Omani Rial', numericCode: '512' },
  { code: 'JOD', symbol: 'د.ا', name: 'Jordanian Dinar', numericCode: '400' },
  { code: 'LBP', symbol: 'ل.ل', name: 'Lebanese Pound', numericCode: '422' },
  { code: 'EGP', symbol: 'ج.م', name: 'Egyptian Pound', numericCode: '818' },
  { code: 'NGN', symbol: '₦', name: 'Nigerian Naira', numericCode: '566' },
  { code: 'KES', symbol: 'KSh', name: 'Kenyan Shilling', numericCode: '404' },
  { code: 'GHS', symbol: 'GH₵', name: 'Ghanaian Cedi', numericCode: '936' },
  { code: 'UGX', symbol: 'USh', name: 'Ugandan Shilling', numericCode: '800' },
  { code: 'TZS', symbol: 'TSh', name: 'Tanzanian Shilling', numericCode: '834' },
  { code: 'ETB', symbol: 'Br', name: 'Ethiopian Birr', numericCode: '230' },
  { code: 'MAD', symbol: 'د.م.', name: 'Moroccan Dirham', numericCode: '504' },
  { code: 'TND', symbol: 'د.ت', name: 'Tunisian Dinar', numericCode: '788' },
  { code: 'DZD', symbol: 'د.ج', name: 'Algerian Dinar', numericCode: '012' },
  { code: 'LYD', symbol: 'ل.د', name: 'Libyan Dinar', numericCode: '434' },
  { code: 'SDG', symbol: 'ج.س.', name: 'Sudanese Pound', numericCode: '938' },
  { code: 'CZK', symbol: 'Kč', name: 'Czech Koruna', numericCode: '203' },
  { code: 'HUF', symbol: 'Ft', name: 'Hungarian Forint', numericCode: '348' },
  { code: 'RON', symbol: 'lei', name: 'Romanian Leu', numericCode: '946' },
  { code: 'BGN', symbol: 'лв', name: 'Bulgarian Lev', numericCode: '975' },
  { code: 'HRK', symbol: 'kn', name: 'Croatian Kuna', numericCode: '191' },
  { code: 'RSD', symbol: 'дин.', name: 'Serbian Dinar', numericCode: '941' },
  { code: 'UAH', symbol: '₴', name: 'Ukrainian Hryvnia', numericCode: '980' },
  { code: 'BYN', symbol: 'Br', name: 'Belarusian Ruble', numericCode: '933' },
  { code: 'KZT', symbol: '₸', name: 'Kazakhstani Tenge', numericCode: '398' },
  { code: 'UZS', symbol: 'so\'m', name: 'Uzbekistani Som', numericCode: '860' },
  { code: 'AZN', symbol: '₼', name: 'Azerbaijani Manat', numericCode: '944' },
  { code: 'GEL', symbol: '₾', name: 'Georgian Lari', numericCode: '981' },
  { code: 'AMD', symbol: '֏', name: 'Armenian Dram', numericCode: '051' },
  { code: 'MDL', symbol: 'L', name: 'Moldovan Leu', numericCode: '498' },
  { code: 'ALL', symbol: 'L', name: 'Albanian Lek', numericCode: '008' },
  { code: 'MKD', symbol: 'ден', name: 'Macedonian Denar', numericCode: '807' },
  { code: 'BAM', symbol: 'KM', name: 'Bosnia-Herzegovina Convertible Mark', numericCode: '977' },
  { code: 'MNT', symbol: '₮', name: 'Mongolian Tögrög', numericCode: '496' },
  { code: 'KGS', symbol: 'с', name: 'Kyrgyzstani Som', numericCode: '417' },
  { code: 'TJS', symbol: 'ЅM', name: 'Tajikistani Somoni', numericCode: '972' },
  { code: 'TMT', symbol: 'T', name: 'Turkmenistani Manat', numericCode: '934' },
  { code: 'AFN', symbol: '؋', name: 'Afghan Afghani', numericCode: '971' },
  { code: 'PKR', symbol: '₨', name: 'Pakistani Rupee', numericCode: '586' },
  { code: 'BDT', symbol: '৳', name: 'Bangladeshi Taka', numericCode: '050' },
  { code: 'LKR', symbol: 'Rs', name: 'Sri Lankan Rupee', numericCode: '144' },
  { code: 'NPR', symbol: '₨', name: 'Nepalese Rupee', numericCode: '524' },
  { code: 'BTN', symbol: 'Nu.', name: 'Bhutanese Ngultrum', numericCode: '064' },
  { code: 'MMK', symbol: 'K', name: 'Myanmar Kyat', numericCode: '104' },
  { code: 'LAK', symbol: '₭', name: 'Lao Kip', numericCode: '418' },
  { code: 'KHR', symbol: '៛', name: 'Cambodian Riel', numericCode: '116' },
  { code: 'VND', symbol: '₫', name: 'Vietnamese Dong', numericCode: '704' },
  { code: 'MOP', symbol: 'MOP$', name: 'Macanese Pataca', numericCode: '446' },
  { code: 'TWD', symbol: 'NT$', name: 'New Taiwan Dollar', numericCode: '901' },
  { code: 'HNL', symbol: 'L', name: 'Honduran Lempira', numericCode: '340' },
  { code: 'GTQ', symbol: 'Q', name: 'Guatemalan Quetzal', numericCode: '320' },
  { code: 'BZD', symbol: 'BZ$', name: 'Belize Dollar', numericCode: '084' },
  { code: 'SVC', symbol: '₡', name: 'Salvadoran Colón', numericCode: '222' },
  { code: 'NIO', symbol: 'C$', name: 'Nicaraguan Córdoba', numericCode: '558' },
  { code: 'CRC', symbol: '₡', name: 'Costa Rican Colón', numericCode: '188' },
  { code: 'PAB', symbol: 'B/.', name: 'Panamanian Balboa', numericCode: '590' },
  { code: 'PYG', symbol: '₲', name: 'Paraguayan Guaraní', numericCode: '600' },
  { code: 'UYU', symbol: '$U', name: 'Uruguayan Peso', numericCode: '858' },
  { code: 'ARS', symbol: '$', name: 'Argentine Peso', numericCode: '032' },
  { code: 'CLP', symbol: '$', name: 'Chilean Peso', numericCode: '152' },
  { code: 'PEN', symbol: 'S/', name: 'Peruvian Sol', numericCode: '604' },
  { code: 'BOB', symbol: 'Bs.', name: 'Bolivian Boliviano', numericCode: '068' },
  { code: 'COP', symbol: '$', name: 'Colombian Peso', numericCode: '170' },
  { code: 'VES', symbol: 'Bs.', name: 'Venezuelan Bolívar', numericCode: '928' },
  { code: 'GYD', symbol: 'G$', name: 'Guyanese Dollar', numericCode: '328' },
  { code: 'SRD', symbol: '$', name: 'Surinamese Dollar', numericCode: '968' },
  { code: 'TTD', symbol: 'TT$', name: 'Trinidad and Tobago Dollar', numericCode: '780' },
  { code: 'JMD', symbol: 'J$', name: 'Jamaican Dollar', numericCode: '388' },
  { code: 'HTG', symbol: 'G', name: 'Haitian Gourde', numericCode: '332' },
  { code: 'DOP', symbol: 'RD$', name: 'Dominican Peso', numericCode: '214' },
  { code: 'CUC', symbol: 'CUC$', name: 'Cuban Convertible Peso', numericCode: '931' },
  { code: 'CUP', symbol: '$', name: 'Cuban Peso', numericCode: '192' },
  { code: 'XCD', symbol: 'EC$', name: 'East Caribbean Dollar', numericCode: '951' },
  { code: 'BBD', symbol: 'Bds$', name: 'Barbadian Dollar', numericCode: '052' },
  { code: 'AWG', symbol: 'ƒ', name: 'Aruban Florin', numericCode: '533' },
  { code: 'ANG', symbol: 'ƒ', name: 'Netherlands Antillean Guilder', numericCode: '532' },
  { code: 'KYD', symbol: 'CI$', name: 'Cayman Islands Dollar', numericCode: '136' },
  { code: 'BMD', symbol: 'BD$', name: 'Bermudian Dollar', numericCode: '060' },
  { code: 'FJD', symbol: 'FJ$', name: 'Fijian Dollar', numericCode: '242' },
  { code: 'WST', symbol: 'T', name: 'Samoan Tālā', numericCode: '882' },
  { code: 'TOP', symbol: 'T$', name: 'Tongan Paʻanga', numericCode: '776' },
  { code: 'SBD', symbol: 'SI$', name: 'Solomon Islands Dollar', numericCode: '090' },
  { code: 'VUV', symbol: 'VT', name: 'Vanuatu Vatu', numericCode: '548' },
  { code: 'NZD', symbol: 'NZ$', name: 'New Zealand Dollar', numericCode: '554' },
  { code: 'PGK', symbol: 'K', name: 'Papua New Guinean Kina', numericCode: '598' },
  { code: 'CDF', symbol: 'FC', name: 'Congolese Franc', numericCode: '976' },
  { code: 'XAF', symbol: 'FCFA', name: 'Central African CFA Franc', numericCode: '950' },
  { code: 'XOF', symbol: 'CFA', name: 'West African CFA Franc', numericCode: '952' },
  { code: 'XPF', symbol: 'CFP', name: 'CFP Franc', numericCode: '953' },
  { code: 'KMF', symbol: 'CF', name: 'Comorian Franc', numericCode: '174' },
  { code: 'DJF', symbol: 'Fdj', name: 'Djiboutian Franc', numericCode: '262' },
  { code: 'GNF', symbol: 'FG', name: 'Guinean Franc', numericCode: '324' },
  { code: 'MGA', symbol: 'Ar', name: 'Malagasy Ariary', numericCode: '969' },
  { code: 'MUR', symbol: '₨', name: 'Mauritian Rupee', numericCode: '480' },
  { code: 'SCR', symbol: '₨', name: 'Seychellois Rupee', numericCode: '690' },
  { code: 'SOS', symbol: 'S', name: 'Somali Shilling', numericCode: '706' },
  { code: 'SSP', symbol: 'SSP', name: 'South Sudanese Pound', numericCode: '728' },
  { code: 'ERN', symbol: 'Nfk', name: 'Eritrean Nakfa', numericCode: '232' },
  { code: 'STN', symbol: 'Db', name: 'São Tomé and Príncipe Dobra', numericCode: '930' },
  { code: 'CVE', symbol: '$', name: 'Cape Verdean Escudo', numericCode: '132' },
  { code: 'GMD', symbol: 'D', name: 'Gambian Dalasi', numericCode: '270' },
  { code: 'GIP', symbol: '£', name: 'Gibraltar Pound', numericCode: '292' },
  { code: 'FKP', symbol: '£', name: 'Falkland Islands Pound', numericCode: '238' },
  { code: 'SHP', symbol: '£', name: 'Saint Helena Pound', numericCode: '654' },
  { code: 'IMP', symbol: '£', name: 'Isle of Man Pound', numericCode: '833' },
  { code: 'JEP', symbol: '£', name: 'Jersey Pound', numericCode: '832' },
  { code: 'GGP', symbol: '£', name: 'Guernsey Pound', numericCode: '831' },
  { code: 'AOA', symbol: 'Kz', name: 'Angolan Kwanza', numericCode: '973' },
  { code: 'BWP', symbol: 'P', name: 'Botswana Pula', numericCode: '072' },
  { code: 'LSL', symbol: 'L', name: 'Lesotho Loti', numericCode: '426' },
  { code: 'NAD', symbol: 'N$', name: 'Namibian Dollar', numericCode: '516' },
  { code: 'SZL', symbol: 'L', name: 'Eswatini Lilangeni', numericCode: '748' },
  { code: 'ZMW', symbol: 'ZK', name: 'Zambian Kwacha', numericCode: '967' },
  { code: 'MWK', symbol: 'MK', name: 'Malawian Kwacha', numericCode: '454' },
  { code: 'ZWL', symbol: 'Z$', name: 'Zimbabwean Dollar', numericCode: '932' },
  { code: 'BIF', symbol: 'FBu', name: 'Burundian Franc', numericCode: '108' },
  { code: 'RWF', symbol: 'FRw', name: 'Rwandan Franc', numericCode: '646' },
  { code: 'MZN', symbol: 'MT', name: 'Mozambican Metical', numericCode: '943' },
  
  // Cryptocurrency tokens for DeFi trading
  { code: 'XLM', symbol: 'XLM', name: 'Stellar Lumens', numericCode: '999' },
  { code: 'USDC', symbol: 'USDC', name: 'USD Coin', numericCode: '998' },
  { code: 'EURC', symbol: 'EURC', name: 'Euro Coin', numericCode: '997' },
  { code: 'AQUA', symbol: 'AQUA', name: 'AQUA Token', numericCode: '996' },
  { code: 'XRP', symbol: 'XRP', name: 'Ripple', numericCode: '995' },
];

// Helper function to find currency by code
export const findCurrencyByCode = (code: string): Currency | undefined => {
  return CURRENCIES.find(currency => currency.code === code.toUpperCase());
};

// Helper function to get display text for currency
export const getCurrencyDisplayText = (currency: Currency): string => {
  return `${currency.symbol} ${currency.code} · ${currency.name}`;
};

// Default currency (USD)
export const DEFAULT_CURRENCY: Currency = CURRENCIES[0];

// Popular currencies for quick access (including crypto tokens)
export const POPULAR_CURRENCIES = [
  'USD', 'EUR', 'XLM', 'USDC', 'GBP', 'JPY', 'CAD', 'AQUA', 'AUD', 'CHF', 'EURC', 'XRP'
].map(code => findCurrencyByCode(code)).filter(Boolean) as Currency[]; 